Repository specify-bdd/specify-core, pull requests merged in 2025-09, with the labels that each got.

#124 NPM publish
  .github/workflows/checks.yaml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .npmrc
  modules/@specify-bdd/plugin-cli/package.json
  modules/@specify-bdd/quick-ref/package.json
  modules/@specify-bdd/specify/package.json
  package.json
  scripts/common.sh
  scripts/github/commit_tag.sh
  scripts/github/merge_develop_to_main.sh
  scripts/github/release.sh
  scripts/github/version.sh
Labels: enhancement

#177 [#155] Implement new exit code for commander errors.
  features/test/basic.feature
  features/test/parallel.feature
  features/test/retry.feature
  modules/@specify-bdd/specify/src/main.ts
Labels: bug

#189 Trying deploy key solution
  .github/workflows/release.yml
  scripts/github/commit_tag.sh
Labels: bug

#190 YAML all the way
  .github/workflows/publish.yml
  .github/workflows/release.yml
  scripts/github/commit_tag.sh
  scripts/github/merge_develop_to_main.sh
  scripts/github/release.sh
  scripts/github/version.sh
Labels: bug

#195 Doc gen fixes and streamlining
  .github/workflows/release.yml
  modules/@specify-bdd/plugin-cli/package.json
  modules/@specify-bdd/plugin-cli/typedoc.html.json
  modules/@specify-bdd/plugin-cli/typedoc.json
  modules/@specify-bdd/plugin-cli/typedoc.markdown.json
  modules/@specify-bdd/quick-ref/package.json
  modules/@specify-bdd/quick-ref/typedoc.html.json
  modules/@specify-bdd/quick-ref/typedoc.json
  modules/@specify-bdd/quick-ref/typedoc.markdown.json
  modules/@specify-bdd/specify/package.json
  modules/@specify-bdd/specify/typedoc.html.json
  modules/@specify-bdd/specify/typedoc.json
  modules/@specify-bdd/specify/typedoc.markdown.json
  package.json
Labels: bug, enhancement
